### ISSUE TITLE
constructing multiple clients creates multiple loghandlers

### ISSUE THREAD

**Issue by slaupster** [ibm-messaging/iot-python#18]
if in a single process you construct more than 1 client, eg:

`loop{

   appCli = ibmiotf.application.Client(opts)

   appCli.connect()

   ...

   appCli.disconnect() `

}

on the second loop you get 2 entries per log, on the third you get 3......

**Comment by durera** [comment]
Never really considered the scenario where a user would run multiple application client instances in a process ... but also haven't done anything to make the class singleton ...

Each instance takes the same logger using the classname

self.logger = logging.getLogger(self.__module__+"."+self.__class__.__name__)

and then proceeds to initialise what it expects to be a pristine logger by adding loghandlers, hence the issues seen here.  What is the application doing that it needs to create multiple instances out of interest?

Easy to fix, making the assumption that one would want to have multiple application instances running in the same process it seems there's two options:

- move the logger to be global for the module rather than per client instance
- pass the clientId into getLogger() as that will provide a unique logger per client in all scenarios except where you run multiple instances of a load balanced application in the same process.

I prefer the latter
